import IISKursovayaRabotaIspravleno1ТоварыEController from '../i-i-s-kursovaya-rabota-ispravleno1-товары-e';

var IISKursovayaRabotaIspravleno1ТоварыENewController = IISKursovayaRabotaIspravleno1ТоварыEController;
export default IISKursovayaRabotaIspravleno1ТоварыENewController;
