//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaIspravleno1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Выбор вида.
    /// </summary>
    // *** Start programmer edit section *** (ВыборВида CustomAttributes)

    // *** End programmer edit section *** (ВыборВида CustomAttributes)
    public enum ВыборВида
    {
        
        // *** Start programmer edit section *** (ВыборВида.Паспорт CustomAttributes)

        // *** End programmer edit section *** (ВыборВида.Паспорт CustomAttributes)
        [Caption("Паспорт")]
        Паспорт,
        
        // *** Start programmer edit section *** (ВыборВида.Загран CustomAttributes)

        // *** End programmer edit section *** (ВыборВида.Загран CustomAttributes)
        [Caption("Загранпаспорт")]
        Загран,
        
        // *** Start programmer edit section *** (ВыборВида.Виза CustomAttributes)

        // *** End programmer edit section *** (ВыборВида.Виза CustomAttributes)
        [Caption("Виза")]
        Виза,
        
        // *** Start programmer edit section *** (ВыборВида.Развлекат CustomAttributes)

        // *** End programmer edit section *** (ВыборВида.Развлекат CustomAttributes)
        [Caption("Развлекательное")]
        Развлекат,
    }
}
